{% set name = "falcon-require-https" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ef26e22d1a30753d9f6cb44fdab329152d6673a9e3ea8d54b27427877e986597

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
    - pytest-runner
  run:
    - python >={{ python_min }}
    - falcon

test:
  requires:
    - python {{ python_min }}
  imports:
    - falcon_require_https

about:
  home: https://github.com/falconry/falcon-require-https
  license: Apache-2.0
  license_family: Apache
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Falcon Middleware: Require HTTPS'
  description: |
    The ``falcon-require-https`` package provides a middleware component for
    sanity-checking that the incoming request was received over HTTPS. While
    the web server is primarily responsibile for enforcing the HTTPS protocol,
    misconfiguration is still a leading cause of security vulnerabilities, and
    so it can be helpful to perform certain additional checks, such as this
    one, within the application layer itself.
  doc_url: https://github.com/falconry/falcon-require-https
  dev_url: https://github.com/falconry/falcon-require-https

extra:
  recipe-maintainers:
    - carlodri
