travis:
  secure:
    BINSTAR_TOKEN: AA1Nui2hpWeCIHa6jiBK1CxDRU6BcJ9BVYLtv73yRm8BafJfjsXOO8UfLHqEOWkJ2nXReq1MHVoF4PCe2uRCN2i8QSuXeebJ9zSa00piSLBChKM4HKAjP/GDrMqRTm2U4j/It8b6dgiTceChUKWbvL0u46pXJ/GD9c8Va7el+f9bpTcqSL9zb0KsR7Z1sMMpUEG3n6jKQtQJEgaySnnHm5/cFy4xUH9voefD8jBGelJzXG1n3f3Bih1fI7kfYWNHOracBMgqpvV2CfZL9Xvk7mKJSIZNusz6SLRDqJm9yNHyUTj+gIwE7+5NhUYI0LhvpHTp0EcX6qSpuUQQPjCFxyAKvw4dfvvhHu9UaPvYnjsjqG7yyetSIxjhrLY9UVSiAzRJ3Pq9aLhBJjk7dRYoArt2DHjhQ+o5j3E+20mQnCdbHU28NUGvJwdk51sQihMp189BCOr3ezdwGvzFqOkcLz4SaKUkuyLsxandXRA1fC+C9C2dztfKFKWVUMFL3c4xc/ftbE3t02uyXm4y5YwLUOdDQZv1ZN4wvuiOfvk4KsoPtvBgr7PQBZx2sgbnaTRL0lMLI9DdrQ5zEm0sgIjq9T7LQ3YjVJ2IMAM8Ja4a+3iXPWOWvZfnlhWi9qfvddRtxeQdDHen+qG1QguI8ClL3mUlwntlO5tDdBgqMjMNGjo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
